spring.datasource.url=jdbc:h2:mem:jobportal
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=mySecretKey
jwt.expiration=86400000
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB